<?php
declare(strict_types=1);
namespace ServiceYar\Users;
use ServiceYar\Auth\Authorization; use ServiceYar\Auth\AuthException; use ServiceYar\Database\Connection; use ServiceYar\Support\Uuid;
final class UserService {
 public static function list(int $uid,int $aid): array { Authorization::requirePermission($uid,'users.view'); Authorization::requireAgencyAccess($uid,$aid); $s=Connection::get()->prepare('SELECT u.id,u.uuid,u.username,u.first_name,u.last_name,u.is_active,u.last_login_at,u.created_at,GROUP_CONCAT(r.title ORDER BY r.id SEPARATOR ", ") roles FROM users u JOIN agency_users au ON au.user_id=u.id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE au.agency_id=:a GROUP BY u.id ORDER BY u.id DESC');$s->execute(['a'=>$aid]);return $s->fetchAll(); }
 public static function save(int $uid,int $aid,array $b,?int $id=null): array {
  Authorization::requirePermission($uid,'users.manage');Authorization::requireAgencyAccess($uid,$aid);$username=trim((string)($b['username']??''));if($username==='')throw new AuthException(422,'نام کاربری الزامی است.','VALIDATION_ERROR');$pdo=Connection::get();
  if($id){$q=$pdo->prepare('UPDATE users SET username=:un,first_name=:fn,last_name=:ln,is_active=:ac WHERE id=:id AND EXISTS(SELECT 1 FROM agency_users WHERE user_id=users.id AND agency_id=:a)');$q->execute(['un'=>$username,'fn'=>$b['firstName']??null,'ln'=>$b['lastName']??null,'ac'=>isset($b['isActive'])?(int)(bool)$b['isActive']:1,'id'=>$id,'a'=>$aid]);}
  else{$pw=(string)($b['password']??'');if(strlen($pw)<8)throw new AuthException(422,'رمز عبور باید حداقل ۸ نویسه باشد.','VALIDATION_ERROR');$q=$pdo->prepare('INSERT INTO users(uuid,username,password_hash,first_name,last_name) VALUES(:u,:un,:pw,:fn,:ln)');$q->execute(['u'=>Uuid::v4(),'un'=>$username,'pw'=>password_hash($pw,PASSWORD_DEFAULT),'fn'=>$b['firstName']??null,'ln'=>$b['lastName']??null]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO agency_users(agency_id,user_id) VALUES(:a,:u)')->execute(['a'=>$aid,'u'=>$id]);}
  if(isset($b['role'])){$s=$pdo->prepare('SELECT id FROM roles WHERE name=:n LIMIT 1');$s->execute(['n'=>(string)$b['role']]);$rid=$s->fetchColumn();if(!$rid)throw new AuthException(422,'نقش نامعتبر است.','VALIDATION_ERROR');$pdo->prepare('DELETE ur FROM user_roles ur JOIN agency_users au ON au.user_id=ur.user_id WHERE ur.user_id=:u AND au.agency_id=:a')->execute(['u'=>$id,'a'=>$aid]);$pdo->prepare('INSERT IGNORE INTO user_roles(user_id,role_id) VALUES(:u,:r)')->execute(['u'=>$id,'r'=>$rid]);}
  return self::find($uid,$aid,$id);
 }
 public static function find(int $uid,int $aid,int $id): array { Authorization::requirePermission($uid,'users.view');Authorization::requireAgencyAccess($uid,$aid);$s=Connection::get()->prepare('SELECT u.id,u.uuid,u.username,u.first_name,u.last_name,u.is_active,u.last_login_at,u.created_at,GROUP_CONCAT(r.name) role_names FROM users u JOIN agency_users au ON au.user_id=u.id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE au.agency_id=:a AND u.id=:u GROUP BY u.id');$s->execute(['a'=>$aid,'u'=>$id]);$x=$s->fetch();if(!$x)throw new AuthException(404,'کاربر پیدا نشد.','NOT_FOUND');return $x; }
}
