CREATE TABLE IF NOT EXISTS guardians (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(200) NOT NULL, mobile VARCHAR(30) NULL, relation_title VARCHAR(50) NULL,
 is_primary TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_guardians_student(student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schools (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE,
 agency_id BIGINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(80) NULL,
 school_type VARCHAR(80) NULL, manager_name VARCHAR(200) NULL, phone VARCHAR(40) NULL,
 address TEXT NULL, latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL,
 region VARCHAR(100) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_schools_agency_active(agency_id,is_active), UNIQUE KEY uq_school_code(agency_id,code),
 CONSTRAINT fk_schools_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS students (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE,
 agency_id BIGINT UNSIGNED NOT NULL, school_id BIGINT UNSIGNED NOT NULL,
 first_name VARCHAR(100) NOT NULL, last_name VARCHAR(120) NOT NULL, national_code VARCHAR(20) NULL,
 grade VARCHAR(50) NULL, mobile VARCHAR(30) NULL, address TEXT NULL,
 latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 deleted_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_students_agency_active(agency_id,is_active), INDEX idx_students_school(school_id),
 CONSTRAINT fk_students_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_students_school FOREIGN KEY(school_id) REFERENCES schools(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, plate VARCHAR(50) NOT NULL,
 model VARCHAR(100) NULL, capacity SMALLINT UNSIGNED NOT NULL DEFAULT 4, is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_vehicle_plate(agency_id,plate), INDEX idx_vehicle_agency(agency_id),
 CONSTRAINT fk_vehicles_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS drivers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, agency_id BIGINT UNSIGNED NOT NULL,
 first_name VARCHAR(100) NOT NULL, last_name VARCHAR(120) NOT NULL, national_code VARCHAR(20) NULL, mobile VARCHAR(30) NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'pending', rating DECIMAL(4,2) NULL, vehicle_id BIGINT UNSIGNED NULL,
 address TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_drivers_agency_status(agency_id,status,is_active),
 CONSTRAINT fk_drivers_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_drivers_vehicle FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, driver_id BIGINT UNSIGNED NOT NULL, document_type VARCHAR(80) NOT NULL,
 document_no VARCHAR(120) NULL, expires_at DATE NULL, status VARCHAR(30) NOT NULL DEFAULT 'valid',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_driver_docs(driver_id), CONSTRAINT fk_driver_docs_driver FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS services (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, agency_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(200) NOT NULL, code VARCHAR(80) NULL, school_id BIGINT UNSIGNED NULL, driver_id BIGINT UNSIGNED NULL,
 capacity SMALLINT UNSIGNED NOT NULL DEFAULT 4, status VARCHAR(30) NOT NULL DEFAULT 'draft',
 start_address TEXT NULL, end_address TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_services_agency_status(agency_id,status,is_active), UNIQUE KEY uq_service_code(agency_id,code),
 CONSTRAINT fk_services_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_services_school FOREIGN KEY(school_id) REFERENCES schools(id) ON DELETE SET NULL,
 CONSTRAINT fk_services_driver FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_students (
 service_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, pickup_address TEXT NULL, pickup_order INT NULL,
 PRIMARY KEY(service_id,student_id), CONSTRAINT fk_service_students_service FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE,
 CONSTRAINT fk_service_students_student FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS packs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, title VARCHAR(200) NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'draft', capacity SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_packs_agency(agency_id), CONSTRAINT fk_packs_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contracts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL,
 contract_no VARCHAR(100) NULL, party_type VARCHAR(30) NOT NULL, party_id BIGINT UNSIGNED NULL,
 start_date DATE NULL, end_date DATE NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'draft',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_contracts_agency_status(agency_id,status), CONSTRAINT fk_contracts_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_work (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, driver_id BIGINT UNSIGNED NOT NULL,
 work_date DATE NOT NULL, service_id BIGINT UNSIGNED NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'pending',
 note TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_driver_work(driver_id,work_date,service_id), INDEX idx_driver_work_agency_date(agency_id,work_date),
 CONSTRAINT fk_driver_work_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_driver_work_driver FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
 CONSTRAINT fk_driver_work_service FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, driver_id BIGINT UNSIGNED NOT NULL,
 payment_date DATE NOT NULL, amount DECIMAL(18,2) NOT NULL, reference_no VARCHAR(120) NULL, note TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_driver_payments_agency_date(agency_id,payment_date),
 CONSTRAINT fk_driver_payments_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_driver_payments_driver FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS school_charges (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, school_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, due_date DATE NULL, status VARCHAR(30) NOT NULL DEFAULT 'open',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_school_charges(agency_id,school_id,status), CONSTRAINT fk_school_charges_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_school_charges_school FOREIGN KEY(school_id) REFERENCES schools(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_charges (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, service_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, due_date DATE NULL, status VARCHAR(30) NOT NULL DEFAULT 'open',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_service_charges(agency_id,service_id,status), CONSTRAINT fk_service_charges_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_service_charges_service FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL,
 party_type VARCHAR(30) NULL, party_id BIGINT UNSIGNED NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'open',
 issue_date DATE NULL, due_date DATE NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_invoices_agency_status(agency_id,status), CONSTRAINT fk_invoices_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, invoice_id BIGINT UNSIGNED NULL,
 amount DECIMAL(18,2) NOT NULL, payment_date DATE NOT NULL, method VARCHAR(50) NULL, reference_no VARCHAR(120) NULL, note TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_payments_agency_date(agency_id,payment_date),
 CONSTRAINT fk_payments_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_payments_invoice FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accounting_accounts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, code VARCHAR(80) NOT NULL, title VARCHAR(255) NOT NULL,
 parent_id BIGINT UNSIGNED NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_account_code(agency_id,code), CONSTRAINT fk_accounts_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_accounts_parent FOREIGN KEY(parent_id) REFERENCES accounting_accounts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accounting_documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, document_no VARCHAR(100) NOT NULL,
 document_date DATE NOT NULL, description TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_accounting_doc(agency_id,document_no), CONSTRAINT fk_accounting_docs_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wallets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, owner_type VARCHAR(30) NOT NULL, owner_id BIGINT UNSIGNED NULL,
 balance DECIMAL(18,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_wallets_agency(agency_id), CONSTRAINT fk_wallets_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, channel VARCHAR(30) NOT NULL DEFAULT 'internal',
 recipient_type VARCHAR(30) NULL, recipient_id BIGINT UNSIGNED NULL, subject VARCHAR(255) NULL, body TEXT NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'queued', sent_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_messages_agency_status(agency_id,status), CONSTRAINT fk_messages_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS files (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, entity_type VARCHAR(80) NULL, entity_id BIGINT UNSIGNED NULL,
 storage_key VARCHAR(500) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NULL, size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
 is_private TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_files_entity(entity_type,entity_id),
 CONSTRAINT fk_files_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_changes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, service_id BIGINT UNSIGNED NOT NULL,
 old_driver_id BIGINT UNSIGNED NULL, new_driver_id BIGINT UNSIGNED NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending',
 reason TEXT NULL, reviewed_by BIGINT UNSIGNED NULL, reviewed_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_driver_changes(agency_id,status), CONSTRAINT fk_driver_changes_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
 CONSTRAINT fk_driver_changes_service FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
