<?php
declare(strict_types=1);
namespace ServiceYar\Holiday;
use ServiceYar\Auth\Authorization; use ServiceYar\Database\Connection;
final class HolidayService {
 public static function list(int $uid,int $aid): array { Authorization::requirePermission($uid,'holidays.view'); Authorization::requireAgencyAccess($uid,$aid); $s=Connection::get()->prepare('SELECT id,title,date_jalali,date_gregorian,holiday_type,is_active FROM holidays WHERE agency_id=:a ORDER BY date_gregorian,date_jalali'); $s->execute(['a'=>$aid]); return $s->fetchAll(); }
 public static function save(int $uid,int $aid,array $b,?int $id=null): array { Authorization::requirePermission($uid,'holidays.manage'); Authorization::requireAgencyAccess($uid,$aid); $title=trim((string)($b['title']??''));$jalali=trim((string)($b['dateJalali']??'')); if($title===''||$jalali==='')throw new \ServiceYar\Auth\AuthException(422,'عنوان و تاریخ جلالی الزامی است.','VALIDATION_ERROR'); $date=$b['dateGregorian']??null; if($id){$q=Connection::get()->prepare('UPDATE holidays SET title=:t,date_jalali=:j,date_gregorian=:g,holiday_type=:ty,is_active=:ac WHERE id=:id AND agency_id=:a');$q->execute(['t'=>$title,'j'=>$jalali,'g'=>$date,'ty'=>$b['type']??'holiday','ac'=>isset($b['isActive'])?(int)(bool)$b['isActive']:1,'id'=>$id,'a'=>$aid]);}else{$q=Connection::get()->prepare('INSERT INTO holidays(agency_id,title,date_jalali,date_gregorian,holiday_type) VALUES(:a,:t,:j,:g,:ty)');$q->execute(['a'=>$aid,'t'=>$title,'j'=>$jalali,'g'=>$date,'ty'=>$b['type']??'holiday']);$id=(int)Connection::get()->lastInsertId();} $s=Connection::get()->prepare('SELECT id,title,date_jalali,date_gregorian,holiday_type,is_active FROM holidays WHERE id=:id AND agency_id=:a');$s->execute(['id'=>$id,'a'=>$aid]);return $s->fetch()?:[]; }
 public static function delete(int $uid,int $aid,int $id): void { Authorization::requirePermission($uid,'holidays.manage'); Authorization::requireAgencyAccess($uid,$aid); Connection::get()->prepare('UPDATE holidays SET is_active=0 WHERE id=:id AND agency_id=:a')->execute(['id'=>$id,'a'=>$aid]); }
}
